using DataFrames
using TextAnalysis
using Languages
using DataFrames

##

e1 = "CONTRATACION DE EJECUCION DE OBRA: CREACION DEL LOCAL COMUNAL MULTIUSOS EN EL SECTOR DE HUARCON TINYAYOC DEL CASERIO DE QUISHU, DISTRITO DE SAN MARCOS - PROVINCIA DE HUARI - DEPARTAMENTO DE ANCASH CON CUI 2566417"
e2 = "CONTRATACION DEL SERVICIO DE CONSULTORIA PARA LA SUPERVISION DE OBRA: 'MEJORAMIENTO DEL COMPLEJO DEPORTIVO EN LA MZ. 19 LT. 01 DEL P.J. MIRAFLORES TERCERA ZONA EN EL DISTRITO DE CHIMBOTE - PROVINCIA DE SANTA - DEPARTAMENTO DE ANCASH' - CUI N°2478580"
e3 = "CONTRATACION DEL SERVICIO DE CONSULTORIA PARA LA SUPERVISION DE LA EJECUCIÓN DEL PROYECTO DE INVERSION ¿CREACION DEL SERVICIO DE PRÁCTICA DEPORTIVA Y/O RECREATIVA EN EL COMPLEJO DEPORTIVO ZOILA AMORETTI DE ODRIA DE LA CALLE LIMA, DISTRITO DE CHAUPIMARCA DE LA PROVINCIA DE PASCO DEL DEPARTAMENTO DE PASCO¿ CON CUI: 2649297"
e4 = "CONTRATACIÓN DE LA EJECUCIÓN DE OBRA: MEJORAMIENTO DE LOS SERVICIOS EDUCATIVOS DE LA IEIPSM 6010288 DE LA LOCALIDAD DE PALMERAS II ZONA DEL DISTRITO DE INDIANA - PROVINCIA DE MAYNAS - DEPARTAMENTO DE LORETO, CON CUI N° 2453261"
e5 = "CONTRATACIÓN DE EJECUCIÓN DE OBRA: MEJORAMIENTO Y AMPLIACIÓN DE LOS SERVICIOS EDUCATIVOS DE LA INSTITUCIÓN EDUCATIVA N° 40150 EN LA LOCALIDAD DE NUEVO HORIZONTE, DISTRITO DE CURAHUASI - PROVINCIA DE ABANCAY - DEPARTAMENTO DE APURÍMAC CON CUI 2716382"

c1 = "CONTRATACIÓN DE LA EJECUCIÓN DE LA OBRA: MEJORAMIENTO DEL SERVICIO DE MOVILIDAD URBANA EN SECTOR 1 DE LA ZONA MONUMENTAL DEL CALLAO, DISTRITO DE CALLAO DE LA PROVINCIA CONSTITUCIONAL DEL CALLAO DEL DEPARTAMENTO DE CALLAO CON CÓDIGO ÚNICO DE INVERSIÓN NO. 2655430"
c2 = "MEJORAMIENTO DEL SERVICIO DE TRANSITABILIDAD PEATONAL Y VEHICULAR DEL PASAJE JOSE OLAYA, AAHH 13 DE AGOSTO DEL DISTRITO DE JACOBO HUNTER - PROVINCIA DE AREQUIPA - DEPARTAMENTO DE AREQUIPA"
c3 = "EJECUCION DE LA OBRA: CREACIÓN DEL SERVICIO DE TRANSITABILIDAD VEHICULAR Y PEATONAL EN LAS VÍAS INTERNAS DEL ASENTAMIENTO HUMANO FLOR DE AMANCAES DEL DISTRITO DE RÍMAC - PROVINCIA DE LIMA - DEPARTAMENTO DE LIMA. CUI N° 2535679"
c4 = "ADQUISICION DE BROCAS, DISCOS Y CLAVOS PARA LA OBRA:'MEJORAMIENTO DEL SERVICIO DE TRANSITABILIDAD PEATONAL Y VEHICULAR EN LA ASOCIACION DE VIVIENDA CERRITO DE HUACSAPATA ZONA A DEL DISTRITO DE PAUCARPATA, PROVINCIA DE AREQUIPA, DEPARTAMENTO DE AREQUIPA"
c5 = "EJECUCIÓN DE LA OBRA: CONSTRUCCIÓN Y MEJORAMIENTO DEL SERVICIO DE TRANSITABILIDAD VEHICULAR Y PEATONAL EN LA CARRETERA RURAL QUE UNE EL CENTRO POBLADO DE YANAHUARA CON LA LOCALIDAD DE MARAS, DISTRITO DE MARAS - PROVINCIA DE URUBAMBA - DEPARTAMENTO DE CUSCO. CUI N° 2498732"

data = DataFrame(text=[e1, e2, e3, e4, e5, c1, c2, c3, c4, c5])

##

function procesar(str::String)
    sd = lowercase(str) |> StringDocument
    language!(sd, Languages.Spanish())
    prepare!(sd, strip_articles)
    prepare!(sd, strip_pronouns)
    prepare!(sd, strip_prepositions)
    prepare!(sd, strip_non_letters)
    return sd
end

transform!(data, :text => ByRow(procesar) => :docu)

##

nbc = NaiveBayesClassifier([:edif, :carre])

for d in data.docu[1:5]
    fit!(nbc, d, :edif)
end
for d in data.docu[6:10]
    fit!(nbc, d, :carre)
end

s_test = [
    "EJECUCIÓN DE OBRA: CREACIÓN DEL LOCAL COMUNAL EN HUARCON TINYAYOC, SAN MARCOS - HUARI, ANCASH.",
    "SUPERVISIÓN DE OBRA: MEJORAMIENTO DEL COMPLEJO DEPORTIVO EN CHIMBOTE, SANTA - ANCASH.",
    "MEJORAMIENTO DEL SERVICIO DE MOVILIDAD EN SECTOR 1, ZONA MONUMENTAL DEL CALLAO.",
    "MEJORAMIENTO DE INFRAESTRUCTURA URBANA EN EL DISTRITO DE CHICLAYO, LAMBAYEQUE.",
    "MEJORAMIENTO DEL LOCAL VEHICULAR CONTRATACION CONTRATACIÓN"
]

for s in s_test
    predict(nbc, s) |> println
end
